services:

  redis:
      image: redis:alpine
      container_name: redis
      ports:
          - "6379:6379"
      restart: unless-stopped

  php-fpm:
    build: ./docker
    depends_on:
        - redis
    volumes:
      - .:/var/www/html
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-xdebug.ini

  web:
      image: nginx
      ports:
          - "83:80"
      volumes:
          - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
          - .:/var/www/html


  postgres:

    image: postgres:13
    ports:
      - 54323:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}

  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
          - "5672:5672"     # порт для приложений
          - "15672:15672"   # порт для веб-интерфейса
      environment:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
      volumes:
          - ./docker/rabbitmq:/var/lib/rabbitmq

